name: Build debian package

on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -yq --no-install-suggests --no-install-recommends devscripts fakeroot equivs dh-python python3-all python3-dateutil python3-requests python3-six
        sudo pip install "invoke>1.4"
    - name: Test building debian package
      run: |
        mk-build-deps -i -s sudo -t 'apt-get -yq' debian/control
        inv deb
